// vue/faq_accordion/src/components/Attribution.vue
<template>
  <div className="attribution">
			Challenge by
			<a
				href="https://www.frontendmentor.io?ref=challenge"
				target="_blank"
				rel="noreferrer"
			>
				Frontend Mentor
			</a>
			. Coded by
			<a
				href="https://github.com/alfredthompsonOvie"
				target="_blank"
				rel="noreferrer"
			>
				Alfred Thompson Ovie
			</a>
			.
		</div>
</template>

<script setup>

</script>

<style scoped>
.attribution {
	font-size: 11px;
	text-align: center;
	grid-column: 2;
	grid-row: 2;
}
.attribution a {
	color: hsl(228, 45%, 44%);
}
</style>

// react/faq_accordion/src/components/ui/Attribution.jsx
import styles from '../styles/Attribution.module.css'
function Attribution() {
	return (
		<div className={styles.attribution}>
			Challenge by{" "}
			<a
				href="https://www.frontendmentor.io?ref=challenge"
				target="_blank"
				rel="noreferrer"
			>
				Frontend Mentor
			</a>
			. Coded by{" "}
			<a
				href="https://github.com/alfredthompsonOvie"
				target="_blank"
				rel="noreferrer"
			>
				Alfred Thompson Ovie
			</a>
			.
		</div>
	);
}

export default Attribution;
